// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tozyxilbmyyoqdhkqkqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvenl4aWxibXl5b3FkaGtxa3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzIxMjIsImV4cCI6MjA3MDYwODEyMn0.Wl_tjPCc3q_LyzNAPcuDDiVYWJafnpwpVfA8Dv_HJYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});